version: '3'

services:
  demo:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://inventario:3306/gestion_inventario?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      CLOUDINARY_NAME: dykuuunmh
      CLOUDINARY_API_KEY: 575898854961468
      CLOUDINARY_API_SECRET: kgGNXoOqan5L4iCbNiuLcNY-tmg
    restart: always
    depends_on:
      inventario:
        condition: service_healthy
  inventario:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: gestion_inventario
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10